import { Button, List, ListItem } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import { useUsers } from "../src/hooks/users";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  const goToUserCreatePage = async () => {
    router.push("/users/create");
  };

  const { userData } = useUsers();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{ display: "flex" }}>
          <Button variant="contained" onClick={() => router.push("/books")}>
            Go to Books Page
          </Button>

          <div style={{ marginLeft: "auto" }}>
            <Button onClick={goToUserCreatePage}>Create User</Button>
            <Button>
              <Link href="/users/signin">Sign In</Link>{" "}
            </Button>
          </div>
        </div>
        <List>
          {userData.map((item: any) => (
            <ListItem>{`${item.firstName} ${item.lastName}`}</ListItem>
          ))}
        </List>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
