import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import styles from "../styles/Home.module.css";
import UsersList from "../src/components/UsersList";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          display: "flex",
          marginTop: "20px",
          justifyContent: "space-between",
        }}
      >
        <Button variant="contained" onClick={() => router.push("/books/add")}>
          Add a new book
        </Button>

        <Button variant="contained" onClick={() => router.push("/books")}>
          View all Books
        </Button>
      </div>

      <UsersList />

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
